In [172]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
df = pd.read_csv('logisticReg.csv')

In [173]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [174]:
from sklearn.model_selection import train_test_split
df.rename(columns={'User ID': 'user'},inplace=True)
df.drop('user',axis=1,inplace=True)
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [175]:
dummy = pd.get_dummies(df.Gender,dtype=int)
df = pd.concat([df,dummy],axis='columns')
df = df.drop('Gender',axis=1)
df

Age  EstimatedSalary  Purchased  Female  Male
0     19            19000          0       0     1
1     35            20000          0       0     1
2     26            43000          0       1     0
3     27            57000          0       1     0
4     19            76000          0       0     1
..   ...              ...        ...     ...   ...
395   46            41000          1       1     0
396   51            23000          1       0     1
397   50            20000          1       1     0
398   36            33000          0       0     1
399   49            36000          1       1     0

[400 rows x 5 columns]

In [176]:
X = df.drop("Purchased", axis=1)
y = df['Purchased']
X_train, X_test, y_train,  y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [177]:
y_train

3      0
18     1
202    1
250    0
274    1
      ..
71     0
106    0
270    0
348    0
102    0
Name: Purchased, Length: 320, dtype: int64

In [232]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='multinomial',penalty='l2',solver='saga')
model.fit(X_train,y_train)

/Users/veerchheda/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(multi_class='multinomial', solver='saga')

In [233]:
y_pred = model.predict(X_test)

In [234]:
score = model.score(X_test,y_test)
from sklearn.metrics import confusion_matrix, accuracy_score

In [235]:
print(score)
print(confusion_matrix(y_test,y_pred))

0.65
[[52  0]
 [28  0]]


In [196]:
df1 = sns.load_dataset('iris')
df1.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [200]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df1['species'] = encoder.fit_transform(df1['species'])

In [201]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [216]:
X1 = df1.iloc[:,0:4]
y1 = df1.iloc[:,-1]
X1_train,X1_test,y1_train,y1_test = train_test_split(X1,y1,test_size=0.2,random_state=33)

In [229]:
model1 = LogisticRegression(multi_class='multinomial',penalty='l2',solver='saga')
model1.fit(X1_train,y1_train)

/Users/veerchheda/Library/Python/3.9/lib/python/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(multi_class='multinomial', solver='saga')

In [230]:
y1_pred = model1.predict(X1_test)

In [231]:
print(accuracy_score(y1_test,y1_pred))
print(confusion_matrix(y1_test,y1_pred))

1.0
[[ 8  0  0]
 [ 0  8  0]
 [ 0  0 14]]
